### ISSUE TITLE
Doc: What is the purpose of these boxes?

### ISSUE THREAD

**Issue by jakubholynet** [phusion/open-vagrant-boxes#23]
Hello, it is not clear to me from the README what is the purpose of these boxes. I believed that it is to run Docker (so that I could `vagrant up; docker <something>`) but that does not seem to be the case (at least `phusion/ubuntu-14.04-amd64` hasn't docker installed). It would be good to clarify that in the docs, I think.

Thank you!

**Comment by FooBarWidget** [comment]
These boxes do not supply Docker. They merely supply Docker friendliness. By this I mean that these boxes supply recent enough kernel versions for use with Docker. Upgrading the kernel and making sure that it's compatible with the VMWare Tools and with the VirtualBox Guest Additions is quite a pain, so with these boxes I streamline the process.

When I started this project, Ubuntu 12.04 was the most recent Ubuntu LTS release, but Ubuntu 12.04 shipped kernel 3.2 while Docker requires at least 3.8. A year later Ubuntu 14.04 came out, but its kernel version was still too old to my liking. In these boxes I made sure that an even more recent kernel is installed.

The VirtualBox Guest Additions and VMWare Tools also had to be patched a little bit to make them work well with what was at the time a very recent kernel version.

Finally, I've also increased the disk space within the images. Most Vagrant boxes only supply 20 GB or so within the image. But when working with Docker, you run out of disk space very quickly because of the way they manage images, containers, AUFS, etc. So in these boxes I've increased the image disk to 40 GB.

**Comment by jakubholynet** [comment]
So the purpose of existence of these images is to make it easy to run Docker on them but Docker is not installed? I.e. the expected use case is use the box, install docker, do whatever you wanted it for. Is there a reason why not pre-install docker if everybody will need it anyway?

**Comment by FooBarWidget** [comment]
> So the purpose of existence of these images is to make it easy to run Docker on them but Docker is not installed? I.e. the expected use case is use the box, install docker, do whatever you wanted it for.

Yes.

> Is there a reason why not pre-install docker if everybody will need it anyway?

Docker moves too fast. If we preinstall it, the preinstalled version will be outdated by the time the user uses the box. That's why I think it's better if they install it themselves.

**Comment by jakubholynet** [comment]
Ok, I see, thank you.

--
Forget software. Strive to make an impact, deliver a valuable change.

(Vær så snill og hjelp meg med å forbedre norsken min – skriftlig og
muntlig. Takk!)

Jakub Holy
Solutions Engineer | +47 966 23 666
Iterate AS | www.iterate.no
The Lean Software Development Consultancy
- http://theholyjava.wordpress.com/ -
8. mai 2015 10:05 skrev "Hongli Lai" <notifications@github.com>:
